Repository ansible-collections/community.kubernetes, pull requests merged in 2020-08, with the labels that each got.

#180 raw: Handle exception raised by underlying APIs
  plugins/module_utils/raw.py
Labels: has_issue, type/bug

#191 Add contrib page
  CONTRIBUTING.md
  README.md
Labels: has_issue, priority/medium

#194 Issue #43: Update README to reflect new Zuul automated tag build and push.
  README.md
Labels: priority/medium

#204 kubectl: correct usage in console
  changelogs/fragments/200_kubectl_fix.yml
  plugins/connection/kubectl.py
Labels: type/bug

#213 fix downstream collection name kubernetes.base -> kubernetes.core
  utils/downstream.sh
Labels: type/bug
