Repository ansible-collections/community.kubernetes, pull requests merged in 2020-10, with the labels that each got.

#245 Add testcase for multi resource template
  changelogs/fragments/243_template.yml
  molecule/default/tasks/template.yml
  molecule/default/templates/pod_template_three.j2
Labels: has_issue

#236 PR #136 follow-up - add test for Helm values files
  molecule/default/roles/helm/files/values.yaml
  molecule/default/roles/helm/tasks/tests_chart.yml
  plugins/modules/helm.py
Labels: priority/high

#26 k8s_rollback: new module
  molecule/default/converge.yml
  molecule/default/tasks/rollback.yml
  plugins/modules/k8s_rollback.py
Labels: type/enhancement

#252 Fixes #250 by defining the FQCN connection plugin name
  plugins/inventory/k8s.py
Labels: has_issue, priority/high, type/bug

#247 Add appVersion check to Helm
  molecule/default/roles/helm/files/appversionless-chart/Chart.yaml
  molecule/default/roles/helm/files/test-chart/Chart.yaml
  molecule/default/roles/helm/tasks/tests_chart/from_local_path.yml
  plugins/modules/helm.py
Labels: has_issue, priority/medium

#255 WIP: Embedded docs clarifications
  plugins/modules/k8s_rollback.py
Labels: type/documentation

#258 Embedded docs clarifications and refinements.
  plugins/inventory/k8s.py
  plugins/modules/helm_plugin_info.py
  plugins/modules/helm_repository.py
  plugins/modules/k8s.py
  plugins/modules/k8s_rollback.py
Labels: type/documentation

#276 Fix default configuration getter in client v12.0.0
  plugins/module_utils/common.py
  tests/integration/targets/kubernetes/tasks/main.yml
  tests/integration/targets/kubernetes/tasks/new_config_getter.yml
Labels: has_issue, priority/medium
