Repository ansible-collections/community.kubernetes, pull requests merged in 2020-09, with the labels that each got.

#211 Add execution environment metadata
  bindep.txt
  requirements.txt
Labels: type/enhancement

#160 k8s_cluster_info: new module
  README.md
  molecule/default/converge.yml
  molecule/default/tasks/cluster_info.yml
  plugins/modules/k8s_cluster_info.py
Labels: priority/medium, type/enhancement

#192 Return status in check mode
  plugins/modules/helm.py
Labels: has_issue, type/enhancement
